monitor=,preferred,auto,1

# Terminal

$terminal = foot
$menu = rofi -show drun

# Startup

exec-once = foot
exec-once = floorp
exec-once = vesktop
exec-once = spotify
exec-once = waybar
exec-once = opensnitch-ui

# Look

general { 
	gaps_in = 0
	gaps_out = 0
	}

# Keybinds

input {
	kb_layout = gb
	follow_mouse = 1
	touchpad {
		natural_scroll = true
		}
	}

# Workspaces

bind = , KP_End, workspace, 1
bind = , KP_Down, workspace, 2
bind = , KP_Next, workspace, 3
bind = , KP_Left, movetoworkspace, 1
bind = , KP_Begin, movetoworkspace, 2
bind = , KP_Right, movetoworkspace, 3

bind = shift, KP_End, workspace, 4
bind = shift, KP_Down, workspace, 5
bind = shift, KP_Next, workspace, 6
bind = shift, KP_Left, movetoworkspace, 4
bind = shift, KP_Begin, movetoworkspace, 5
bind = shift, KP_Right, movetoworkspace, 6


# Open apps / execs

bind = , KP_Home, exec, $terminal
bind = , KP_Up, exec, vesktop
bind = , KP_Prior, exec, floorp

bind = shift, KP_Prior, exec, spotify
bind = shift, KP_Up, exec, steam
bind = shift, KP_Home, exec, foot -e nano ~/.config/hypr/hyprland.conf
bind = Mod5, comma, exec, foot -e sudo nano /etc/nixos/configuration.nix

bind = Mod5, KP_End, exec, opensnitch-ui

bind = Mod5, K, exec, pkill -f $(hyprctl activewindow -j | jq -r '.initialClass')
bind = Mod5, Space, exec, $menu

# Windowed windows

bind = Mod5, P, pin
bind = Mod5, F, togglefloating

bind = ctrl, left, movewindow, l
bind = ctrl, right, movewindow, r
bind = ctrl, up, movewindow, u
bind = ctrl, down, movewindow, d

binde = Mod4, left, resizeactive, -20 0
binde = Mod4, right, resizeactive, 20 0
binde = Mod4, up, resizeactive, 0 -20
binde = Mod4, down, resizeactive, 0 20
